<a href="https://colab.research.google.com/github/geulsujiwoo/HanyangUniv_PBL/blob/main/3%EC%A3%BC%EC%B0%A8/3%EC%A3%BC%EC%B0%A8%EC%BD%94%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.full((3, 5), 1.0).requires_grad_()

In [3]:
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

In [5]:
x.size()

torch.Size([3, 5])

In [7]:
dropout = nn.Dropout(p = 0.75)

In [8]:
y = dropout(x)

In [9]:
y

tensor([[0., 0., 0., 0., 0.],
        [0., 4., 4., 0., 0.],
        [0., 0., 0., 4., 4.]], grad_fn=<MulBackward0>)

In [13]:
l = y.norm(2, 1).sum()

In [14]:
l.backward()

In [15]:
x.grad

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 2.8284, 2.8284, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 2.8284, 2.8284]])

In [16]:
x.grad.zero_()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [17]:
x = torch.full((3, 5), 1.0)

In [19]:
x[1, 2] = 0

In [20]:
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
x.requires_grad_()

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

In [22]:
l = x.norm(2,1).sum()

In [23]:
l

tensor(6.4721, grad_fn=<SumBackward0>)

In [24]:
l.backward()

In [25]:
x.grad

tensor([[0.4472, 0.4472, 0.4472, 0.4472, 0.4472],
        [0.5000, 0.5000, 0.0000, 0.5000, 0.5000],
        [0.4472, 0.4472, 0.4472, 0.4472, 0.4472]])